#!/bin/sh
while read -r file
do
    case "$1" in
        "r")
            convert -rotate 90 "$file" "$file" ;;
        "c")
            xclip -selection clipboard -t image/png -i "$file" ;;
        "w")
            hsetroot -center "$file" ;;
    esac
done
