# Autogenerated config.py
# Documentation:
#   qute://help/configuring.html
#   qute://help/settings.html

# Uncomment this to still load settings configured via autoconfig.yml
# config.load_autoconfig()

# Backend to use to display websites. qutebrowser supports two different
# web rendering engines / backends, QtWebKit and QtWebEngine. QtWebKit
# was discontinued by the Qt project with Qt 5.6, but picked up as a
# well maintained fork: https://github.com/annulen/webkit/wiki -
# qutebrowser only supports the fork. QtWebEngine is Qt's official
# successor to QtWebKit. It's slightly more resource hungry than
# QtWebKit and has a couple of missing features in qutebrowser, but is
# generally the preferred choice.
# Type: String
# Valid values:
#   - webengine: Use QtWebEngine (based on Chromium).
#   - webkit: Use QtWebKit (based on WebKit, similar to Safari).
c.backend = 'webengine'

# Turn on Qt HighDPI scaling. This is equivalent to setting
# QT_AUTO_SCREEN_SCALE_FACTOR=1 in the environment. It's off by default
# as it can cause issues with some bitmap fonts. As an alternative to
# this, it's possible to set font sizes and the `zoom.default` setting.
# Type: Bool
c.qt.highdpi = False

# Load images automatically in web pages.
# Type: Bool
c.content.images = True

# Allow JavaScript to open new tabs without user interaction.
# Type: Bool
c.content.javascript.can_open_tabs_automatically = True

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'file://*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'chrome://*/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'qute://*/*')

# Enable plugins in Web pages.
# Type: Bool
c.content.plugins = True

# Search engines which can be used via the address bar. Maps a search
# engine name (such as `DEFAULT`, or `ddg`) to a URL with a `{}`
# placeholder. The placeholder will be replaced by the search term, use
# `{{` and `}}` for literal `{`/`}` signs. The search engine named
# `DEFAULT` is used when `url.auto_search` is turned on and something
# else than a URL was entered to be opened. Other search engines can be
# used by prepending the search engine name to the search term, e.g.
# `:open google qutebrowser`.
# Type: Dict
c.url.searchengines = {'DEFAULT': 'https://www.google.com/search?hl=en&q={}'}

# Page(s) to open at the start.
# Type: List of FuzzyUrl, or FuzzyUrl
c.url.start_pages = ['https://www.google.com/']

# Text color of the completion widget. May be a single color to use for
# all columns or a list of three colors, one for each column.
# Type: List of QtColor, or QtColor
c.colors.completion.fg = '#ffffff'

# Background color of the completion widget for odd rows.
# Type: QssColor
c.colors.completion.odd.bg = '#3f3f3f'

# Background color of the completion widget for even rows.
# Type: QssColor
c.colors.completion.even.bg = '#3f3f3f'

# Foreground color of completion widget category headers.
# Type: QtColor
c.colors.completion.category.fg = '#ffa500'

# Background color of the completion widget category headers.
# Type: QssColor
c.colors.completion.category.bg = '#3f3f3f'

# Top border color of the completion widget category headers.
# Type: QssColor
c.colors.completion.category.border.top = '#3f3f3f'

# Bottom border color of the completion widget category headers.
# Type: QssColor
c.colors.completion.category.border.bottom = '#3f3f3f'

# Foreground color of the selected completion item.
# Type: QtColor
c.colors.completion.item.selected.fg = '#ffffff'

# Background color of the selected completion item.
# Type: QssColor
c.colors.completion.item.selected.bg = '#26c549'

# Top border color of the completion widget category headers.
# Type: QssColor
c.colors.completion.item.selected.border.top = '#26c549'

# Bottom border color of the selected completion item.
# Type: QssColor
c.colors.completion.item.selected.border.bottom = '#26c549'

# Foreground color of the matched text in the completion.
# Type: QssColor
c.colors.completion.match.fg = '#B981F4'

# Color of the scrollbar handle in the completion view.
# Type: QssColor
c.colors.completion.scrollbar.fg = '#ffffff'

# Color of the scrollbar in the completion view.
# Type: QssColor
c.colors.completion.scrollbar.bg = '#3f3f3f'

# Background color for the download bar.
# Type: QssColor
c.colors.downloads.bar.bg = '#3f3f3f'

# Color gradient start for download text.
# Type: QtColor
c.colors.downloads.start.fg = '#3f3f3f'

# Color gradient start for download backgrounds.
# Type: QtColor
c.colors.downloads.start.bg = '#ffa500'

# Color gradient end for download text.
# Type: QtColor
c.colors.downloads.stop.fg = '#3f3f3f'

# Color gradient stop for download backgrounds.
# Type: QtColor
c.colors.downloads.stop.bg = '#0f91f5'

# Foreground color for downloads with errors.
# Type: QtColor
c.colors.downloads.error.fg = '#f50f50'

# Font color for hints.
# Type: QssColor
c.colors.hints.fg = '#3f3f3f'

# Background color for hints. Note that you can use a `rgba(...)` value
# for transparency.
# Type: QssColor
c.colors.hints.bg = '#ffa500'

# Font color for the matched part of hints.
# Type: QssColor
c.colors.hints.match.fg = '#ffffff'

# Text color for the keyhint widget.
# Type: QssColor
c.colors.keyhint.fg = '#ffffff'

# Highlight color for keys to complete the current keychain.
# Type: QssColor
c.colors.keyhint.suffix.fg = '#ffffff'

# Background color of the keyhint widget.
# Type: QssColor
c.colors.keyhint.bg = '#3f3f3f'

# Foreground color of an error message.
# Type: QssColor
c.colors.messages.error.fg = '#3f3f3f'

# Background color of an error message.
# Type: QssColor
c.colors.messages.error.bg = '#7ff145'

# Border color of an error message.
# Type: QssColor
c.colors.messages.error.border = '#7ff145'

# Foreground color of a warning message.
# Type: QssColor
c.colors.messages.warning.fg = '#3f3f3f'

# Background color of a warning message.
# Type: QssColor
c.colors.messages.warning.bg = '#B981F4'

# Border color of a warning message.
# Type: QssColor
c.colors.messages.warning.border = '#B981F4'

# Foreground color of an info message.
# Type: QssColor
c.colors.messages.info.fg = '#ffffff'

# Background color of an info message.
# Type: QssColor
c.colors.messages.info.bg = '#3f3f3f'

# Border color of an info message.
# Type: QssColor
c.colors.messages.info.border = '#3f3f3f'

# Foreground color for prompts.
# Type: QssColor
c.colors.prompts.fg = '#ffffff'

# Border used around UI elements in prompts.
# Type: String
c.colors.prompts.border = '#3f3f3f'

# Background color for prompts.
# Type: QssColor
c.colors.prompts.bg = '#3f3f3f'

# Background color for the selected item in filename prompts.
# Type: QssColor
c.colors.prompts.selected.bg = '#0f91f5'

# Foreground color of the statusbar.
# Type: QssColor
c.colors.statusbar.normal.fg = '#7ff145'

# Background color of the statusbar.
# Type: QssColor
c.colors.statusbar.normal.bg = '#3f3f3f'

# Foreground color of the statusbar in insert mode.
# Type: QssColor
c.colors.statusbar.insert.fg = '#3f3f3f'

# Background color of the statusbar in insert mode.
# Type: QssColor
c.colors.statusbar.insert.bg = '#B981F4'

# Foreground color of the statusbar in passthrough mode.
# Type: QssColor
c.colors.statusbar.passthrough.fg = '#3f3f3f'

# Background color of the statusbar in passthrough mode.
# Type: QssColor
c.colors.statusbar.passthrough.bg = '#0f91f5'

# Foreground color of the statusbar in private browsing mode.
# Type: QssColor
c.colors.statusbar.private.fg = '#3f3f3f'

# Background color of the statusbar in private browsing mode.
# Type: QssColor
c.colors.statusbar.private.bg = '#3f3f3f'

# Foreground color of the statusbar in command mode.
# Type: QssColor
c.colors.statusbar.command.fg = '#ffffff'

# Background color of the statusbar in command mode.
# Type: QssColor
c.colors.statusbar.command.bg = '#3f3f3f'

# Foreground color of the statusbar in private browsing + command mode.
# Type: QssColor
c.colors.statusbar.command.private.fg = '#ffffff'

# Background color of the statusbar in private browsing + command mode.
# Type: QssColor
c.colors.statusbar.command.private.bg = '#3f3f3f'

# Foreground color of the statusbar in caret mode.
# Type: QssColor
c.colors.statusbar.caret.fg = '#3f3f3f'

# Background color of the statusbar in caret mode.
# Type: QssColor
c.colors.statusbar.caret.bg = '#26c549'

# Foreground color of the statusbar in caret mode with a selection.
# Type: QssColor
c.colors.statusbar.caret.selection.fg = '#3f3f3f'

# Background color of the statusbar in caret mode with a selection.
# Type: QssColor
c.colors.statusbar.caret.selection.bg = '#B981F4'

# Background color of the progress bar.
# Type: QssColor
c.colors.statusbar.progress.bg = '#B981F4'

# Default foreground color of the URL in the statusbar.
# Type: QssColor
c.colors.statusbar.url.fg = '#ffffff'

# Foreground color of the URL in the statusbar on error.
# Type: QssColor
c.colors.statusbar.url.error.fg = '#7ff145'

# Foreground color of the URL in the statusbar for hovered links.
# Type: QssColor
c.colors.statusbar.url.hover.fg = '#ffffff'

# Foreground color of the URL in the statusbar on successful load
# (http).
# Type: QssColor
c.colors.statusbar.url.success.http.fg = '#0f91f5'

# Foreground color of the URL in the statusbar on successful load
# (https).
# Type: QssColor
c.colors.statusbar.url.success.https.fg = '#7ff145'

# Foreground color of the URL in the statusbar when there's a warning.
# Type: QssColor
c.colors.statusbar.url.warn.fg = '#ffa500'

# Background color of the tab bar.
# Type: QtColor
c.colors.tabs.bar.bg = '#3f3f3f'

# Color gradient start for the tab indicator.
# Type: QtColor
c.colors.tabs.indicator.start = '#B981F4'

# Color gradient end for the tab indicator.
# Type: QtColor
c.colors.tabs.indicator.stop = '#0f91f5'

# Color for the tab indicator on errors.
# Type: QtColor
c.colors.tabs.indicator.error = '#f50f50'

# Foreground color of unselected odd tabs.
# Type: QtColor
c.colors.tabs.odd.fg = '#ffffff'

# Background color of unselected odd tabs.
# Type: QtColor
c.colors.tabs.odd.bg = '#3f3f3f'

# Foreground color of unselected even tabs.
# Type: QtColor
c.colors.tabs.even.fg = '#ffffff'

# Background color of unselected even tabs.
# Type: QtColor
c.colors.tabs.even.bg = '#3f3f3f'

# Foreground color of selected odd tabs.
# Type: QtColor
c.colors.tabs.selected.odd.fg = '#3f3f3f'

# Background color of selected odd tabs.
# Type: QtColor
c.colors.tabs.selected.odd.bg = '#ffffff'

# Foreground color of selected even tabs.
# Type: QtColor
c.colors.tabs.selected.even.fg = '#3f3f3f'

# Background color of selected even tabs.
# Type: QtColor
c.colors.tabs.selected.even.bg = '#ffffff'

# Font used in the completion widget.
# Type: Font
c.fonts.completion.entry = '12pt DejaVuSans Mono'

# Font used in the completion categories.
# Type: Font
c.fonts.completion.category = '12pt DejaVuSans Mono'

# Font used for the hints.
# Type: Font
c.fonts.hints = 'DejaVuSans Mono'

# Font used for error messages.
# Type: Font
c.fonts.messages.error = '10pt DejaVuSans Mono'

# Font used for prompts.
# Type: Font
c.fonts.prompts = 'DejaVuSans Mono'

# Font used in the statusbar.
# Type: Font
c.fonts.statusbar = 'DejaVuSans Mono'

# Font used in the tab bar.
# Type: QtFont
c.fonts.tabs = 'DejaVuSans Mono'

# Bindings for normal mode
config.bind('M', 'hint links spawn mpv {hint-url}')
config.bind('m', 'spawn mpv {url}')
