#! /bin/zsh

sxhkd &
# Compositor
compton &
# Wallpaper
nitrogen --restore &
# Paineis
~/.config/polybar/launch.sh
# Carrega arquivo de configuração X e carrega o tema de cursor.
xrdb ~/.Xresources
xsetroot -cursor_name left_ptr
# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
# MPD daemon start (if no other user instance exists)
# [ ! -s ~/.config/mpd/pid ] && mpd
# Ajuste de temperatura da cor da tela
redshift-gtk &
# Notification Daemon
dunst &
# Welcome
dunstify "Bem Vindo SeraphyBR"




bspc monitor eDP1  -d I II III IV V VI VII VIII IX X
#bspc monitor HDMI1 -d VI VII VIII IX X

#bspc config click_to_focus true
bspc config focus_follows_pointer true
bspc config border_width         4
bspc config window_gap          12

#bspc config remove_disabled_monitors true
#bspc config remove_unplugged_monitors true

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color "#FFFFFF"
bspc config active_border_color "#556B2F"
bspc config focused_border_color "#00FF7F"
bspc config presel_border_color "#18fe64"
bspc config urgent_border_color "#FF4500"

bspc rule -a manjaro-hello desktop='^1' state=floating follow=on  center=true
manjaro-hello &

bspc rule -a Zathura state=tiled
# Fix Java Windows
export _JAVA_AWT_WM_NONREPARENTING=1


