#!/bin/bash

sxhkd &
# Compositor
compton -b &
# Wallpaper
hsetroot -center ~/DotFiles/Wallpapers/fern_leaf_plant_green_119970_1920x1080.jpg & 
# Paineis
~/.config/polybar/launch.sh &
# Carrega arquivo de configuração X e carrega o tema de cursor.
xrdb ~/.Xresources &
xsetroot -cursor_name left_ptr &
# Mapa de teclado brasileiro
setxkbmap -model abnt2 -layout br -variant abnt2 &
#Polkit
/usr/libexec/polkit-gnome-authentication-agent-1 &
# Ajuste de temperatura da cor da tela
redshift-gtk &
# Plugin que desabilita escurecimento de tela
caffeine-indicator &
# Thunar Daemom 
thunar --daemon &
# Notification Daemon
dunst &
~/DotFiles/Scripts/battery-status.sh &
# Music Player Daemon
mpd &
# Welcome
dunstify "Bem Vindo ${USER^}!" & 
# Auto lockscreen
xautolock -time 15 -locker 'betterlockscreen -l' & 

bspc monitor eDP-1  -d I II III IV V VI VII VIII IX X
#bspc monitor HDMI-1 -d VI VII VIII IX X

#bspc config click_to_focus true
bspc config pointer_modifier mod4 # Super key to mouse actions
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc config focus_follows_pointer true
bspc config border_width         5
bspc config border_radius        2
bspc config window_gap          14

#bspc config remove_disabled_monitors true
#bspc config remove_unplugged_monitors true

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color "#c9c9c9"
bspc config active_border_color "#556B2F"
bspc config focused_border_color "#76DD6C"
bspc config presel_border_color "#9DFF5F"
bspc config urgent_border_color "#FF4500"
bspc config presel_feedback_color "#9DFF5F"

bspc rule -a '*:libreoffice' state=tiled
bspc rule -a '*:soffice' state=tiled 
bspc rule -a Zathura state=tiled
bspc rule -a Firefox state=floating
bspc rule -a Firefox:Navigator state=tiled
