#!/bin/sh
#  ______
# |   __ \.-----.-----.--.--.--.--------.----.----.
# |   __ <|__ --|  _  |  |  |  |        |   _|  __|
# |______/|_____|   __|________|__|__|__|__| |____|
#               |__|

mydotfiles="$HOME/Git/DotFiles"
dot_s="$mydotfiles/Scripts"
dot_i="$mydotfiles/Images"

sxhkd &
# Compositor
picom -b &
# Wallpaper
"$dot_s"/wallblur/wallblur.sh -o "$dot_i"/Wallpapers &
# Painels
~/.config/polybar/launch.sh &
# Read Xresources and Fix cursor on bspwm
xrdb ~/.Xresources &
xsetroot -cursor_name left_ptr &
#Polkit
/usr/libexec/polkit-gnome-authentication-agent-1 &
# Adjusts the color temperature of screen
/usr/libexec/geoclue-2.0/demos/agent &
redshift-gtk &
# https://github.com/caffeine-ng/caffeine-ng
caffeine &
# Notification Daemon
dunst &
"$dot_s"/battery-status.sh &
# Music Player Daemon
mpd &
"$dot_s"/mpd_notify.sh &
# Auto mount devices
udiskie --smart-tray &

# Welcome
dunstify "Bem Vindo ${USER^}!" &
# Set random lockscreen image
"$dot_s"/betterlockscreen/betterlockscreen -u "$dot_i"/Lockscreen &
# Auto lockscreen
xautolock -time 15 -locker "$dot_s/betterlockscreen/betterlockscreen -l" &

# Bspwm config section

bspc monitor eDP-1-1 -d I II III IV V VI VII VIII IX X
#bspc config click_to_focus true
bspc config pointer_modifier mod4 # Super key to mouse actions
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc config focus_follows_pointer true
bspc config border_width         5
bspc config window_gap          14

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc config automatic_scheme longest_side
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color "#c9c9c9"
bspc config active_border_color "#76DD6C"
bspc config focused_border_color "#76DD6C"
bspc config urgent_border_color "#FF4500"
bspc config presel_border_color "#9DFF5F"
bspc config presel_feedback_color "#9DFF5F"

bspc rule -a '*:libreoffice' state=tiled
bspc rule -a '*:soffice' state=tiled
bspc rule -a Zathura state=tiled
bspc rule -a Emacs state=tiled
bspc rule -a Firefox state=floating
bspc rule -a Firefox:Navigator state=tiled

# srandr for handle displays output
sleep 2
srandrd -e "$dot_s"/display_handler.sh &
